---
- name: Build Docker Image from Dockerfile
  hosts: build-node
  become: yes

  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present

    - name: Copy Dockerfile to build node
      copy:
        src: /home/user/repo1/Dockerfile  # Полный путь к Dockerfile на мастер-ноде
        dest: /tmp/Dockerfile  # Путь назначения на build-ноду

    - name: Build Docker image
      command: docker build -t my_appv1_image:latest /tmp
