---
- name: Build Docker Image from Dockerfile
  hosts: build
  become: yes

  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present

    - name: Copy Dockerfile to build node
      copy:
        src: /home/user/repo1/Dockerfile 
        dest: /tmp/Dockerfile  

    - name: Build Docker image
      command: docker build -t my_appv1_image:latest /tmp

    - name: Login to Docker Hub
      shell: echo dckr_pat_WubHX6YlWiPkYExk7k7VJ6Q8020 | docker login  -u aamitv --password-stdin

    - name: Tag Docker image for registry
      command: docker tag my_appv1_image:latest aamitv/boxfuse:latest

    - name: Push Docker image to Docker Hub
      command: docker push aamitv/boxfuse:latest

- name: Download docker image and run container
  hosts: app
  become: yes
  tasks:
    - name: install docker
      apt:
        name: docker.io
        state: present

    - name: Download image
      command: docker pull aamitv/boxfuse:latest


    - name: Run docker container
      command: docker run -d --name my_api_container -p 8080:8080 aamitv/boxfuse:latest
